name: dartified
description: Life-saving helpers for working with JavaScript libraries when compiling Dart/Flutter to Web.
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
